### ISSUE TITLE
URL for get-available-server-imports refer to not existing resource

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/APIDocs#13]
Hi @bryanfriedman @jruckle ,

During our development we found that URL provided in [get-available-server-imports](https://github.com/CenturyLinkCloud/APIDocs/blob/master/Servers/get-available-server-imports.md) always returns **404**. 

Then after investigation we found that correct URL for receive list of server import is `https://api.ctl.io/v2/vmImport/{accountAlias}/{dataCenterId}/available`.

Best Regards, 
Ilya

**Comment by bryanfriedman** [comment]
Thanks, just updated the doc accordingly. Fix 5d82264.
