### ISSUE TITLE
API missing appfog roles

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/APIDocs#19]
https://www.centurylinkcloud.com/api-docs/v1/#users

users API doesn't say what value to use for appfog roles.  I've been unable to determine this as user list outputs from the API using our CLI tool don't reflect a value on appfog user roles.  I need to update all our 1,000+ sandbox users to have rights to play with appfog in bulk

**Comment by osbornm** [comment]
@csterwa want to take this?

**Comment by csterwa** [comment]
@chrislittle I've put this onto the team's Slack channel to see what we can do here. Will update once I know more.

**Comment by csterwa** [comment]
@chrislittle - it looks like we will need to update the Platform users API to add AppFog user role as part of the roles enumeration. Also, we would have to add each of them to the spaces. When done through the UI this is taken care of when the user is added as a member of the region. The team is going to have to think about a solution for this use case.

What is your timeline for needing this? Yesterday or can you wait for next Platform release?

**Comment by chrislittle** [comment]
We can wait a single release but some other automated option as a work around would be gladly accepted due to the large volume of users/sellers in sandbox (ccts). Naturally a full API model is ideal for bulk edits of current users

**Comment by csterwa** [comment]
@chrislittle We've got a card on our Trello board to implement this in the near future. I'll keep you posted.

**Comment by chrislittle** [comment]
@csterwa is there an update on this?  its been 4 months
