### ISSUE TITLE
Anchor tags seem to be missing collection name

### ISSUE THREAD

**Issue by rseroter** [CenturyLinkCloud/APIDocs#24]
The left nav links to something like Get Groups (https://www.ctl.io/api-docs/v2/#groups-get-group) differ from the anchor link next to the API doc itself (https://www.ctl.io/api-docs/v2/#get-group). The former resolves the right place, the latter doesn't send the user to the API doc.

**Comment by nathanyoung** [comment]
The class name is prepended to the function to ensure that all anchor links are unique. In your example, how is the latter generated?

**Comment by rseroter** [comment]
On the latter, I get that link by clicking the anchor button next to the article name on the right.

**Comment by nathanyoung** [comment]
![screen shot 2015-07-30 at 11 18 37 am](https://cloud.githubusercontent.com/assets/1447339/8991351/fc88a3da-36ac-11e5-811a-1327af11e9cb.png)

**Comment by mattfordham** [comment]
Acknowledge this. Will hopefully have a fix today.

**Comment by mattfordham** [comment]
Commit below should fix this...

https://github.com/CenturyLinkCloud/PublicPlatform/commit/7e6ec3176c3528344dbec16ec66b8b800337c5c9
