### ISSUE TITLE
Start / Stop Maintainance expect Server Name (not ID)

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/APIDocs#3]
Hi!

We found some interesting behaviour of Start / Stop Maintainance method. 
When we put ID of server as request JSON (we received this ID from Get-Server and it seems like "wa1aliaswb02") method does not work. And for make it working we need to provide name of server (received from Get-Server and it seems like "WA1ALIASWB02").

ID and name looks similar and differents only in case of letters. But really if put ID (as described here) method will not works as expected, need to put name.

**Comment by bryanfriedman** [comment]
Thanks for pointing this out. Moving this to our internal issue tracking list.
