### ISSUE TITLE
[Data Centre Bare Metal Capabilities] Storage Definition and Operating Systems Definition switched

### ISSUE THREAD

**Issue by grrtrr** [CenturyLinkCloud/APIDocs#43]
This refers to [Data Centers -> Get Data Center Bare Metal Capabilities](https://github.com/CenturyLinkCloud/APIDocs/blob/master/Data%20Centers/get-data-center-bare-metal-capabilities.md)

* the contents of "Storage Definition" and "OperatingSystems Definition" are switched
* 'type' in 'Storage Definition' has description of 'Drive capacity in gigabytes'
* 'capacityGB' in 'OperatingSystems Definition' has description of 'OS type'

**Comment by richardcase** [comment]
@grrtrr can this now be closed?

**Comment by grrtrr** [comment]
Yes, thank you.
